[project]
name = "theprogramiristlethalcompanymodpack"
version = "0.1.0"
description = "theprogramiristlethalcompanymodpack"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "httpx>=0.28.1",
    "prettytable>=3.12.0",
    "tqdm>=4.67.1",
]
